#!/bin/sh

cat << EOF > generate.go
package main

//go:generate go-bindata-assetfs -nomemcopy $(bfs assets -type d|xargs)
EOF

go generate && env GOOS=illumos GOARCH=amd64 go build -v && rsync novncproxy root@minerva:/opt/novncproxy/ && rm -f novncproxy bindata.go
